server:
  port: 8081

app:
  frontend:
    url: https://app.com.thinkemr

spring:
  application:
    name: thinkemr-user-service

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${keycloak.base-url}/realms/${keycloak.realm}/protocol/openid-connect/token/introspect
          client-id: ${keycloak.client-id}
          client-secret: ${keycloak.client-secret}

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        naming:
          physical-startegy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC

  liquibase:
    change-log: classpath:db/master.yaml
    enabled: true

  config:
    import: optional:configserver
  cloud:
    config:
      uri: http:localhost:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: basic
    notification:
      url: http://localhost:8002/

keycloak:
  realm: development
  base-url: http://localhost:8090/
  auth-url: ${keycloak.base-url}/
  client-id: thinkemrdev
  client-secret: StAI7XIgjdq1kd9ludDlT1JiovJb80Aw
